### ISSUE TITLE
Related Content

### ISSUE THREAD

**Issue by yatil** [w3c/wai-website-components#16]
Do we need this in addition to #4?

https://app.zeplin.io/project.html#pid=58da7fb05d831f2441ed1c0a&sid=58da8005df494cca2cc124a4

**Comment by vuxcaleb** [comment]
Built and PR: https://github.com/w3c/wai-website-components/pull/20 

Let me know if you see any issues.

**Comment by yatil** [comment]
Thanks, @vuxcaleb, I’ll take a look at it tomorrow :-)
